name: build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CURRENT_VERSION: "3.6.0"
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout gatling/gatling
        uses: actions/checkout@v5
        with:
          repository: gatling/gatling
          ref: main
          path: gatling

      - name: Checkout gatling/gatling-highcharts
        uses: actions/checkout@v5
        with:
          path: gatling-highcharts

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt/launchers
            ~/.sbt/boot
            ~/.sbt/preloaded
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      - name: Publish gatling locally
        working-directory: gatling
        run: |
          sbt -Dproject.version="$CURRENT_VERSION" publishLocal

      - name: Test
        working-directory: gatling-highcharts
        run: |
          sbt \
            -Dproject.version="$CURRENT_VERSION" \
            "all headerCheck" \
            "all scalafmtSbtCheck" \
            "all scalafmtCheckAll" \
            "all scalafixAll --check" \
            "test"
